[build-system]
requires = [
	"setuptools>=42",
    "Cython",
    "numpy",
]

build-backend = "setuptools.build_meta"

[tool.cibuildwheel.macos]
repair-wheel-command = [
  "delocate-wheel -w {dest_dir} -v {wheel}",
]
