# recipe file for use by rattler-config in building conda packages for pyimfit

context:
  version: 1.0.1

package:
  name: pyimfit
  version: ${{ version }}

# https://pypi.io/packages/source/{ package_name_first_letter }/{ package_name }/{ package_name }-{ package_version }.tar.gz

source:
#  url: https://pypi.io/packages/source/p/pyimfit/pyimfit-${{ version }}.tar.gz
#  sha256: c36b38203786f1c955b6c7f2e95288b761ba789cef006ea42cd68201a052958e
  git: https://github.com/perwin/pyimfit.git


build:
  number: 0
  script: python -m pip install . -vv


# Note the difference with conda-build: we do *not* need/want a separate requirements:build
# list; instead, all of those requirements should go under host. If we have a build
# requirements list, then the output package is built without the Python wheel, and
# will not import.
requirements:
  host:
    - python
    - pip
    - scons
    - nomkl
    - numpy<2.0
    - scipy
  run:
    - python
    - nomkl
    - numpy
    - scipy
    - requests

# test:
#   imports:
#     - pyimfit

about:
  homepage: https://github.com/perwin/pyimfit
  repository: https://github.com/perwin/pyimfit
  license: GPL-3.0
  license_family: GPL
  summary: Python wrapper for the astronomical image-fitting program Imfit
  description: Python wrapper for Imfit, a program for fast fitting of astronomica images
  documentation: https://pyimfit.readthedocs.io
